name = "hono-cloudflare-auth"
main = "src/index.ts"
compatibility_date = "2024-10-31"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
JWT_SECRET = "${JWT_SECRET}"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1